// Doxy

#ifndef TRNITY_TRACK6000_RADIO_CONFIG_H_
    #define TRINITY_TRACK6000_RADIO_CONFIG_H_

#define RADIO_DEFAULT_CHANNEL          0x20
#define RADIO_DEFAULT_DATA_RATE        NRF_DR_2MBPS
#define RADIO_DEFAULT_TX_POWER         NRF_PWR_0DBM
#define RADIO_DEFAULT_ADDRESS          {0xFE,0xFE,0xFE,0xFE,0xFE}
#define RADIO_DEFAULT_PAYLOAD_SIZE_32  (1<<5)

#endif // TRNITY_TRACK6000_RADIO_CONFIG_H_